export const OK = "OK"
export const CREATED = "CREATED"
export const BAD_REQUEST = "BAD_REQUEST"
export const UNAUTHORIZED = "UNAUTHORIZED"
export const FORBIDDEN = "FORBIDDEN"
export const NOT_FOUND = "NOT_FOUND"
export const CONFLICT = "CONFLICT"
export const VALIDATION_ERROR = "VALIDATION_ERROR"
export const INTERNAL_ERROR = "INTERNAL_ERROR"

export type ReplyCode =
  | "OK"
  | "CREATED"
  | "BAD_REQUEST"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "CONFLICT"
  | "VALIDATION_ERROR"
  | "INTERNAL_ERROR"
